### PR TITLE
add Japanese

### PR DESCRIPTION
**Pull request by Cahell**
I create language file for you.
I hope you like it

### CODE REVIEW

**Comment by goragod** [comment]
with Thank

**Comment by Cahell** [comment]
you are welcome:)

**Comment by Cahell** [comment]
oh, btw, if you don't mind, could you translate https://github.com/KinagaCMS/KinagaCMS into Thai?

**Comment by goragod** [comment]
Okay, let's get some time. This is the Songkran Festival.

**Comment by Cahell** [comment]
thank you!
festival nice! have fun!

**Pull request merged**
